version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: "compose-app-web"
    ports:
     - "7002:5000"
    depends_on:
     - "db"
    networks: 
      - my-net
  db:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    restart: always
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    container_name: "compose-app-web-db"
    volumes: 
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_USER: sa
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_PASSWORD: 123123
    networks: 
      - my-net
networks: 
  my-net:
    driver: bridge